# Generated by Django 5.2.7 on 2026-01-19 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable', '0005_reportcard'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student_rank', 'date_of_repo_generation')},
        ),
    ]
