# Generated by Django 5.2.7 on 2026-01-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable', '0006_alter_reportcard_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='date_of_repo_generation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
