# Generated by Django 5.2.7 on 2026-01-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable', '0007_alter_reportcard_date_of_repo_generation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together=set(),
        ),
    ]
