# Generated by Django 5.2.7 on 2026-01-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable', '0008_alter_reportcard_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Student_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentid',
            name='studentid',
            field=models.CharField(),
        ),
    ]
