# Generated by Django 5.2.7 on 2026-01-26 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable', '0009_alter_student_student_age_alter_studentid_studentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2026, 1, 26, 17, 15, 11, 553579, tzinfo=datetime.timezone.utc), unique=True),
            preserve_default=False,
        ),
    ]
