# Generated by Django 5.2.7 on 2026-01-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable', '0010_recipe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
